version: '3.8'

services:
  postgis:
    image: postgis/postgis:latest
    container_name: postgis-docker
    environment:
      POSTGRES_PASSWORD: postpass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/initdb:/docker-entrypoint-initdb.d
      - ${HOME}/docker/volumes/postgis:/var/lib/postgresql/data

  mlflow:
    build:
      context: ./environment/mlflow
    container_name: mlflow-server
    ports:
      - "8825:8825"
    command: >
      mlflow server
      --backend-store-uri postgresql://postgres:postpass@postgis-docker:5432/mlflow
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      -p 8825
    volumes:
      - ${HOME}/docker/volumes/mlflow:/mlflow
    depends_on:
      postgis:
        condition: service_healthy

volumes:
  postgis_data:
  mlflow_artifacts:
